import { type BankObject, type BrandObject, CardInfoLocation, CardNetwork, type CardObject, CardRedemption, CardType } from "$lib/types";

const card_table:{[Key: string]:CardObject} = {
  "10001" : { "card_name": "Chase Sapphire Preferred Card", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "sapphire-preferred", "card_link": "https://creditcards.chase.com/a1/24Q3/sapphire/dual?CELL=6D4C&jp_cmp=cc/Sapphire+Preferred_Brand_Exact_Sapphire+Preferred_SEM_US_NA_Standard_NA/sea/p56274819573/Chase+Sapphire+Preferred&gclsrc=aw.ds&ds_rl=1253080&gad_source=1&gbraid=0AAAAAD3FB7i1j2vzRyV0CxUdUgHrJuQmk&gclid=CjwKCAjw6JS3BhBAEiwAO9waF9yKk2CALzk0nVjp4TeajfjDcmaoPLnzKOkLuhYELmydDj7L1f6H3RoCVD8QAvD_BwE&gclsrc=aw.ds", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.49-28.49", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_weight": 13, "card_color": "#08345d", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "21.49-28.49", "card_lpapr": 29.99, "card_subv": 60000, "card_subq": 4000, "card_subt": 3, "card_auc": 0 },
  "10002" : { "card_name": "Chase Sapphire Reserve", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "sapphire-reserve", "card_link": "https://creditcards.chase.com/a1/24Q3/sapphire/dual?CELL=6D4C&jp_cmp=cc/Sapphire+Preferred_Brand_Exact_Sapphire+Preferred_SEM_US_NA_Standard_NA/sea/p56274819573/Chase+Sapphire+Preferred&gclsrc=aw.ds&ds_rl=1253080&gad_source=1&gbraid=0AAAAAD3FB7i1j2vzRyV0CxUdUgHrJuQmk&gclid=CjwKCAjw6JS3BhBAEiwAO9waF9yKk2CALzk0nVjp4TeajfjDcmaoPLnzKOkLuhYELmydDj7L1f6H3RoCVD8QAvD_BwE&gclsrc=aw.ds", "card_image": null, "card_af": 550, "card_ftf": 0, "card_btf": "5|5", "card_apr": "22.49-29.49", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_weight": 13, "card_color": "#102e48", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "22.49-29.49", "card_lpapr": 29.99, "card_subv": 60000, "card_subq": 4000, "card_subt": 3, "card_auc": 75 },
  "10003" : { "card_name": "American Express Gold Card", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "amex-gold", "card_link": "https://card.americanexpress.com/d/gold-card/", "card_image": null, "card_af": 325, "card_ftf": 0, "card_apr": "21.24-29.24", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_weight": 15, "card_color": "#c1b064", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 90000, "card_subq": 6000, "card_subt": 6, "card_auc": 0 },
  "10004" : { "card_name": "Capital One Venture Rewards Mastercard", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "venture-rewards", "card_link": "https://www.capitalone.com/credit-cards/venture/", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": 4, "card_apr": "19.99|26.24|29.99", "card_caf": "5|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#031839", "card_redemption": CardRedemption.Miles, "card_caapr": 29.99, "card_subv": 75000, "card_subq": 4000, "card_subt": 3, "card_auc": 0 },
  "10005" : { "card_name": "QuicksilverOne from Capital One Mastercard", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "quicksilver-one", "card_link": "https://www.capitalone.com/credit-cards/quicksilverone/", "card_image": null, "card_af": 39, "card_ftf": 0, "card_btf": 4, "card_apr": 29.99, "card_caf": "5|5", "card_lpf": 40, "card_chip": true, "card_ttp": true, "card_color": "#7892a8", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": 29.99, "card_auc": 0 },
  "10006" : { "card_name": "Citi Double Cash Card", "card_bank": "Citi", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "citi-double-cash", "card_link": "https://www.citi.com/usc/LPACA/Citi/Cards/DoubleCash/ps_A/index.html", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "19.24-29.24", "card_caf": "10|5", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#218a61", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "19.24-29.24", "card_lpapr": 29.99, "card_subv": 20000, "card_subq": 1500, "card_subt": 6},
  "10007" : { "card_name": "Discover it Cash Back", "card_bank": "Discover", "card_network": CardNetwork.Discover, "card_type": CardType.Personal, "card_url": "discover-it", "card_link": "https://www.discover.com/credit-cards/cash-back/it-card.html", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 5, "card_apr": "18.24-28.24", "card_caf": "10|5", "card_lpf": "<=41", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#81c1d9", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "18.24-28.24", },
  "10008" : { "card_name": "Discover it Miles", "card_bank": "Discover", "card_network": CardNetwork.Discover, "card_type": CardType.Personal, "card_url": "discover-it-miles", "card_link": "https://www.discover.com/credit-cards/travel/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 5, "card_apr": "18.24-28.24", "card_caf": "10|5", "card_lpf": "<=41", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#1257ab", "card_redemption": CardRedemption.Miles, "card_caapr": 29.99, "card_btapr": "18.24-28.24", },
  "10009" : { "card_name": "Blue Cash Preferred Card from American Express", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "amex-blue", "card_link": "https://card.americanexpress.com/d/blue-cash-preferred-credit-card/", "card_image": null, "card_af": 95, "card_ftf": 2.7, "card_btf": "5|3", "card_apr": "19.24-29.99", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#273653", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "19.24-29.99", "card_lpapr": 29.99, "card_subv": 30000, "card_subq": 3000, "card_subt": 6},
  "10010" : { "card_name": "Wells Fargo Active Cash Card", "card_bank": "Wells Fargo", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "wf-active-cash", "card_link": "https://creditcards.wellsfargo.com/cards/active-cash-credit-card/", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "20.24|25.24|29.99", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#684e52", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "20.24|25.24|29.99", "card_subv": 20000, "card_subq": 500, "card_subt": 3},
  "10011" : { "card_name": "Bank of America Customized Cash Rewards Credit Card", "card_bank": "Bank of America", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "bofa-ccr", "card_link": "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": 4, "card_apr": "19.24-29.24", "card_caf": 4, "card_lpf": "<=40", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_weight": 5, "card_color": "#b31a26", "card_redemption": CardRedemption.CashBack, "card_caapr": "22.24-29.24", "card_btapr": "19.24-29.24", "card_lpapr": 29.99, "card_subv": 20000, "card_subq": 1000, "card_subt": 3},
  "10012" : { "card_name": "US Bank Altitude Go Visa Signature Card", "card_bank": "US Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "usb-altitude", "card_link": "https://www.usbank.com/credit-cards/altitude-go-visa-signature-credit-card.html", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|3", "card_apr": "18.24-29.24", "card_caf": "10|5", "card_lpf": "<=41", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 12, "card_color": "#cd1d2a", "card_redemption": CardRedemption.Points, "card_caapr": 32.24, "card_btapr": "18.24-29.24", "card_lpapr": 0, "card_subv": 20000, "card_subq": 1000, "card_subt": 3},
  "10013" : { "card_name": "Hilton Honors American Express Aspire Card", "card_bank": "American Express", "card_brand": "Hilton", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "hilton-honors", "card_link": "https://card.americanexpress.com/d/hilton-honors-aspire-credit-card/", "card_image": null, "card_af": 550, "card_ftf": 0, "card_apr": "20.99-29.99", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#0c2b4f", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 150000, "card_subq": 6000, "card_subt": 6},
  "10014" : { "card_name": "Marriott Bonvoy Brilliant American Express Card", "card_bank": "American Express", "card_brand": "Marriott", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "marriott-brilliant", "card_link": "https://card.americanexpress.com/d/bonvoy-brilliant-credit-card/", "card_image": null, "card_af": 650, "card_ftf": 0, "card_apr": "20.99-29.99", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 15, "card_color": "#080808", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 185000, "card_subq": 6000, "card_subt": 6},
  "10015" : { "card_name": "The Platinum Card from American Express", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "amex-platinum", "card_link": "https://card.americanexpress.com/d/platinum-card/", "card_image": null, "card_af": 695, "card_ftf": 0, "card_apr": "21.24-29.24", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 17, "card_color": "#dddfe1", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 175000, "card_subq": 8000, "card_subt": 6},
  "10016" : { "card_name": "Citi Strata Premier Card", "card_bank": "Citi", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "citi-premier", "card_link": "https://www.citi.com/usc/lpaca/citi/rewards/stratapremier/ps/index.html", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.24-29.24", "card_caf": "10|5", "card_chip": true, "card_ttp": true, "card_color": "#76767b", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "21.24-29.24", "card_lpapr": 29.99, "card_subv": 70000, "card_subq": 3000, "card_subt": 3},
  "10017" : { "card_name": "Chase Freedom Flex", "card_bank": "Chase Bank", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "chase-freedom-flex", "card_link": "https://creditcards.chase.com/a1/freedom/CFDFlex924", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "20.49-29.24", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_embossed": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#1a9cd5", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "20.49-29.24", "card_lpapr": 29.99, "card_subv": 15000, "card_subq": 500, "card_subt": 3},
  "10018" : { "card_name": "Chase Freedom Unlimited", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "chase-freedom-unlimited", "card_link": "https://creditcards.chase.com/a1/freedom/CFDUnl924", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "20.49-29.24", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_embossed": true, "card_material": "Plastic", "card_il": CardInfoLocation.Front, "card_ttp": true, "card_weight": 5, "card_color": "#22396a", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "20.49-29.24", "card_lpapr": 29.99, "card_subv": 15000, "card_subq": 500, "card_subt": 3},
  "10019" : { "card_name": "Capital One SavorOne Cash Rewards Credit Card", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "C1-SavorOne", "card_link": "https://www.capitalone.com/credit-cards/savorone-dining-rewards/", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": 4, "card_apr": "19.99|26.24|29.99", "card_caf": "5|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#cf7b52", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "19.99|26.24|29.99", "card_subv": 20000, "card_subq": 500, "card_subt": 3, "card_auc": 0 },
  "10020" : { "card_name": "PenFed Pathfinder Rewards Visa Signature", "card_bank": "Pentagon Federal", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "penfed-pathfinder", "card_link": "https://www.penfed.org/credit-cards/pathfinder-rewards-visa", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": 3, "card_apr": 17.99, "card_caf": 0, "card_lpf": "<=28", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#7e8285", "card_redemption": CardRedemption.Points, "card_caapr": 17.99, "card_btapr": 17.99, "card_subv": 50000, "card_subq": 3000, "card_subt": 3},
  "10021" : { "card_name": "TD Bank TD Cash Credit Card", "card_bank": "TD Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "TD-cash", "card_link": "https://www.td.com/us/en/personal-banking/credit-cards/cash-card", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|3", "card_apr": "20.24|25.24|30.24", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#285032", "card_redemption": CardRedemption.CashBack, "card_caapr": 30.49, "card_btapr": "20.24|25.24|30.24", "card_subv": 15000, "card_subq": 1000, "card_subt": 3},
  "10022" : { "card_name": "Discover it Student Cash Back", "card_bank": "Discover", "card_network": CardNetwork.Discover, "card_type": CardType.Student, "card_url": "discover-it-student", "card_link": "https://www.discover.com/credit-cards/student-credit-card/it-card.html?ICMPGN=SUBNAV_CCP_STUDENT_IT", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 5, "card_apr": "18.24-27.24", "card_caf": "10|5", "card_lpf": "<=41", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#81c1d9", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "18.24-27.24", "card_lpapr": 0, },
  "10023" : { "card_name": "Capital One SavorOne Student Cash Rewards Credit Card", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Student, "card_url": "C1-SavorOne-student", "card_link": "https://www.capitalone.com/credit-cards/savorone-student/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 4, "card_apr": "19.99|26.24|29.99", "card_caf": "5|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#cf7b52", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "19.99|26.24|29.99", "card_subv": 5000, "card_subq": 100, "card_subt": 3},
  "10024" : { "card_name": "Chase Freedom Rise", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "chase-freedom-rise", "card_link": "https://creditcards.chase.com/a1/freedom/rise24", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": 26.99, "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#1185b2", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": 26.99, "card_lpapr": 29.99, },
  "10025" : { "card_name": "Bank of America Unlimited Cash Rewards for Students", "card_bank": "Bank of America", "card_network": CardNetwork.Visa, "card_type": CardType.Student, "card_url": "bofa-unlimited", "card_link": "https://www.bankofamerica.com/credit-cards/products/unlimited-cash-back-student-credit-card/", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": 4, "card_apr": "19.24-29.24", "card_caf": 4, "card_lpf": "<=40", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#96979a", "card_redemption": CardRedemption.CashBack, "card_caapr": "22.24-29.24", "card_btapr": "19.24-29.24", "card_lpapr": 29.99, "card_subv": 20000, "card_subq": 1000, "card_subt": 3},
  "10026" : { "card_name": "Chase Ink Business Cash Credit Card", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Business, "card_url": "chase-ink-cash", "card_link": "https://creditcards.chase.com/a1/DAO/ink-business/universal/cash/24/900", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "18.49-24.49", "card_caf": "15|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#646a71", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "18.49-24.49", "card_lpapr": 29.99, "card_subv": 35000, "card_subq": 3000, "card_subt": 3},
  "10027" : { "card_name": "Chase Ink Business Unlimited Credit Card", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Business, "card_url": "chase-ink-unlimited", "card_link": "https://creditcards.chase.com/a1/DAO/ink-business/universal/24/900", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": "5|5", "card_apr": "18.49-24.49", "card_caf": "15|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#272e35", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "18.49-24.49", "card_lpapr": 29.99, "card_subv": 90000, "card_subq": 6000, "card_subt": 3},
  "10028" : { "card_name": "American Express Business Gold Card", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "amex-gold-business", "card_link": "https://creditcard.americanexpress.com/d/business-gold-card/", "card_image": null, "card_af": 375, "card_ftf": 0, "card_apr": "19.49-28.49", "card_lpf": "39|2.99", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_color": "#c1b064", "card_redemption": CardRedemption.Points, "card_lpapr": 29.99, "card_subv": 100000, "card_subq": 15000, "card_subt": 3},
  "10029" : { "card_name": "Capital One Spark Cash Plus", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Business, "card_url": "C1-spark", "card_link": "https://www.capitalone.com/small-business/credit-cards/spark-cash-plus/", "card_image": null, "card_af": 150, "card_ftf": 0, "card_caf": "5|5", "card_lpf": "2.99%", "card_chip": true, "card_ttp": true, "card_color": "#033f23", "card_redemption": CardRedemption.CashBack, "card_subv": 200000, "card_subq": 30000, "card_subt": 3},
  "10030" : { "card_name": "American Express Blue Business Cash Card", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "amex-blue-business", "card_link": "https://creditcard.americanexpress.com/d/business-bluecash-credit-card/", "card_image": null, "card_af": 0, "card_ftf": 2.7, "card_btf": "5|3", "card_apr": "18.49-26.49", "card_lpf": "<=39", "card_chip": true, "card_ttp": true, "card_color": "#295488", "card_redemption": CardRedemption.CashBack, "card_lpapr": 29.99, "card_subv": 25000, "card_subq": 3000, "card_subt": 3},
  "10031" : { "card_name": "Chase Ink Business Preferred Credit Card", "card_bank": "Chase Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Business, "card_url": "chase-ink-preferred", "card_link": "https://creditcards.chase.com/a1/DAO/ink-business/universal/preferred/24/900", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.24-26.24", "card_caf": "15|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#122a4f", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "21.24-26.24", "card_lpapr": 29.99, "card_subv": 90000, "card_subq": 8000, "card_subt": 3},
  "10032" : { "card_name": "Capital One Spark Miles for Business", "card_bank": "Capital One", "card_network": CardNetwork.MasterCard, "card_type": CardType.Business, "card_url": "C1-spark-miles", "card_link": "https://www.capitalone.com/small-business/credit-cards/spark-miles/", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": 0, "card_apr": 26.24, "card_caf": "5|5", "card_lpf": "<=39", "card_chip": true, "card_ttp": true, "card_color": "#013773", "card_redemption": CardRedemption.Points, "card_caapr": 26.24, "card_lpapr": 34.65, "card_subv": 50000, "card_subq": 4500, "card_subt": 3},
  "10033" : { "card_name": "The Business Platinum Card from American Express", "card_bank": "American Express", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "amex-platinum-business", "card_link": "https://creditcard.americanexpress.com/d/business-platinum-card/", "card_image": null, "card_af": 695, "card_ftf": 0, "card_apr": "19.49-28.49", "card_lpf": "39|2.99", "card_chip": true, "card_ttp": true, "card_color": "#dddfe1", "card_redemption": CardRedemption.Points, "card_lpapr": 29.99, "card_subv": 150000, "card_subq": 20000, "card_subt": 3},
  "10034" : { "card_name": "U.S. Bank Business Leverage Visa Signature Card", "card_bank": "US Bank", "card_network": CardNetwork.Visa, "card_type": CardType.Business, "card_url": "usb-business-leverage", "card_link": "https://www.usbank.com/business-banking/business-credit-cards/business-leverage-rewards-credit-card.html", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": "5|5", "card_apr": "19.99-26.99", "card_caf": "10|5", "card_lpf": "<=41", "card_chip": true, "card_ttp": true, "card_color": "#326f78", "card_redemption": CardRedemption.CashBack, "card_caapr": 32.24, "card_btapr": "19.99-26.99", "card_lpapr": 29.99, "card_subv": 75000, "card_subq": 7500, "card_subt": 4},
  "10035" : { "card_name": "Bank of America Business Advantage Customized Cash Rewards Mastercard", "card_bank": "Bank of America", "card_network": CardNetwork.MasterCard, "card_type": CardType.Business, "card_url": "bofa-business-ccr", "card_link": "https://promotions.bankofamerica.com/smallbusiness/smallbusinesscards", "card_image": null, "card_af": 0, "card_ftf": 3, "card_btf": 4, "card_apr": "18.49-28.49", "card_caf": 4, "card_lpf": "<=49", "card_chip": true, "card_ttp": true, "card_color": "#b31a26", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.49, "card_btapr": "18.49-28.49", "card_lpapr": 0, "card_subv": 30000, "card_subq": 3000, "card_subt": 3},
  "10036" : { "card_name": "Apple Card", "card_bank": "Goldman Sachs", "card_brand": "Apple", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "apple", "card_link": "https://learn.applecard.apple/apply", "card_image": null, "card_af": 0, "card_ftf": 0, "card_apr": "19.24-29.49", "card_lpf": 0, "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.NoNumber, "card_ttp": true, "card_weight": 15, "card_color": "e6e3e5", "card_redemption": CardRedemption.CashBack, },
  "10037" : { "card_name": "Seen Mastercard", "card_bank": "Coastal Community Bank", "card_brand": "Seen.com", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "seen_mastercard", "card_link": "https://seen.com", "card_image": null, "card_af": "0-75", "card_ftf": 0, "card_apr": "29.99|35.99", "card_redemption": CardRedemption.None, "card_lpf": 25, "card_chip": true, "card_ttp": true, "card_color": "#051569", "card_lpapr": 0},
  "10038" : { "card_name": "Costco Anywhere Visa", "card_bank": "Citi", "card_brand": "Costco", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "costco", "card_link": "https://www.citi.com/usc/LPACA/COSTCO/cards/Dual/ps/index.html", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": "5|5", "card_apr": 20.49, "card_caf": "10|5", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#76767e", "card_redemption": CardRedemption.StoreCredit,  "card_caapr": 29.99, "card_btapr": 20.49, "card_lpapr": 29.99, },
  "10039" : { "card_name": "Costco Anywhere Visa Business", "card_bank": "Citi", "card_brand": "Costco", "card_network": CardNetwork.Visa, "card_type": CardType.Business, "card_url": "costco-businesss", "card_link": "https://www.citi.com/usc/LPACA/COSTCO/cards/Dual/ps/index.html", "card_image": null, "card_af": 0, "card_ftf": 0, "card_apr": 20.49, "card_caf": "10|5", "card_chip": true, "card_ttp": true, "card_color": "#76767e", "card_redemption": CardRedemption.StoreCredit, "card_caapr": 29.99, "card_lpapr": 29.99, },
  "10040" : { "card_name": "Bilt World Elite Mastercard", "card_bank": "Wells Fargo", "card_brand": "Bilt", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "bilt", "card_link": "https://www.biltrewards.com/card", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.49|24.49|29.49", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_color": "#171718", "card_redemption": CardRedemption.Points, "card_caapr": 29.24, "card_btapr": "21.49|24.49|29.49", },
  "10041" : { "card_name": "REI Co-op Mastercard", "card_bank": "Capital One", "card_brand": "REI", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "rei", "card_link": "https://www.capitalone.com/credit-cards/rei/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 3, "card_apr": "19.24|26.24|30.24", "card_caf": "5|5", "card_lpf": "<=40", "card_chip": true, "card_material": "Plastic", "card_ttp": true, "card_color": "#225140", "card_redemption": CardRedemption.StoreCredit,  "card_caapr": 30.24, "card_btapr": "19.24|26.24|30.24", },
  "10042" : { "card_name": "Marriott Bonvoy Bold Credit Card from Chase", "card_bank": "Chase Bank", "card_brand": "Marriott", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "marriott-bold", "card_link": "https://creditcards.chase.com/a1/marriottbonvoybold/aep/LTO", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.49-28.49", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#788fa9", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "21.49-28.49", "card_lpapr": 29.99, "card_subv": 60000, "card_subq": 2000, "card_subt": 3},
  "10043" : { "card_name": "Marriott Bonvoy Boundless Credit Card from Chase", "card_bank": "Chase Bank", "card_brand": "Marriott", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "marriott-boundless", "card_link": "https://creditcards.chase.com/a1/marriottbonvoyboundless/aep/LTO", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": "5|5", "card_apr": "21.49-28.49", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#21385b", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_btapr": "21.49-28.49", "card_lpapr": 29.99, "card_subv": 125000, "card_subq": 5000, "card_subt": 3},
  "10044" : { "card_name": "Marriott Bonvoy Bevy American Express Card", "card_bank": "American Express", "card_brand": "Marriott", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Personal, "card_url": "marriott-bevy", "card_link": "https://www.americanexpress.com/en-us/credit-cards/details/personal/marriott/marriott-bonvoy-american-express-cards/ep-mar-mic-1759", "card_image": null, "card_af": 250, "card_ftf": 0, "card_apr": "20.99-29.99", "card_caf": "10|5", "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#50504f", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 155000, "card_subq": 5000, "card_subt": 6},
  "10045" : { "card_name": "Marriott Bonvoy Business American Express Card", "card_bank": "American Express", "card_brand": "Marriott", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "marriott-business", "card_link": "https://www.marriott.com/credit-cards/marriott-bonvoy-business-american-express-card.mi", "card_image": null, "card_af": 125, "card_apr": "20.99-29.99", "card_caf": "5|3", "card_lpf": "<=39", "card_chip": true, "card_ttp": true, "card_color": "#8293a8", "card_redemption": CardRedemption.Points, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 250000, "card_subq": 8000, "card_subt": 6},
  "10046" : { "card_name": "Amazon Prime Visa", "card_bank": "Chase Bank", "card_brand": "Amazon", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "amazon", "card_link": "https://www.amazon.com/dp/BT00LN946S", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": "5|4", "card_apr": "20.49-29.24", "card_caf": "5|4", "card_lpf": "<=39", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 13, "card_color": "#c0c0c0", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "20.49-29.24", "card_lpapr": 29.99, "card_subv": 5000, },
  "10047" : { "card_name": "Amazon Store Card", "card_bank": "Synchrony", "card_brand": "Amazon", "card_network": CardNetwork.None, "card_type": CardType.Personal, "card_url": "amazon-store", "card_link": "https://www.amazon.com/dp/B008A0GNA8", "card_image": null, "card_af": 0, "card_apr": 29.99, "card_lpf": "<=40", "card_chip": true, "card_ttp": true, "card_color": "#c7c6c6", "card_redemption": CardRedemption.CashBack, },
  "10048" : { "card_name": "Amazon Secured Card", "card_bank": "Synchrony", "card_brand": "Amazon", "card_network": CardNetwork.None, "card_type": CardType.Personal, "card_url": "amazon-secured", "card_link": "https://www.amazon.com/gp/product/B084KP3NG6", "card_image": null, "card_af": 0, "card_apr": 10, "card_lpf": "<=5", "card_chip": true, "card_ttp": true, "card_color": "#d6d9da", "card_redemption": CardRedemption.CashBack, },
  "10049" : { "card_name": "Robinhood Gold Card", "card_bank": "Coastal Community Bank", "card_brand": "Robinhood", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "robinhood", "card_link": "https://robinhood.com/creditcard/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 0, "card_apr": "19.99-29.99", "card_caf": "5|10", "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 17, "card_color": "#b29f6e", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_btapr": "19.99-29.99", },
  "10050" : { "card_name": "BMW Card", "card_bank": "Elan Financial Services", "card_brand": "BMW", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "bmw", "card_link": "https://www.mybmwcreditcard.com/credit/bmw_credit_benefits.do", "card_image": null, "card_af": 0, "card_ftf": 3, "card_apr": "19.24-32.24", "card_caf": "5|10", "card_lpf": "<=41", "card_chip": true, "card_ttp": true, "card_color": "#067eb6", "card_redemption": CardRedemption.Points, "card_caapr": 32.24, "card_btapr": "19.24-32.24", "card_subv": 5000, "card_subq": 500, "card_subt": 3},
  "10051" : { "card_name": "BMW Precision Card", "card_bank": "Elan Financial Services", "card_brand": "BMW", "card_network": CardNetwork.MasterCard, "card_type": CardType.Personal, "card_url": "bmw-precision", "card_link": "https://www.mybmwcreditcard.com/credit/bmw_precision_credit_benefits.do", "card_image": null, "card_af": 99, "card_ftf": 0, "card_btf": "5|3", "card_apr": "19.24-32.24", "card_caf": "5|10", "card_lpf": "<=41", "card_chip": true, "card_ttp": true, "card_color": "#1d6398", "card_redemption": CardRedemption.Points, "card_caapr": 32.24, "card_btapr": "19.24-32.24", "card_subv": 7500, "card_subq": 1000, "card_subt": 3},
  "10052" : { "card_name": "Amazon Business American Express Card", "card_bank": "American Express", "card_brand": "Amazon", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "amazon-business", "card_link": "https://www.amazon.com/gp/product/B07984JN3L/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_apr": "19.49-27.49", "card_caf": "5|3", "card_lpf": "<=39", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_color": "#495d6b", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 10000, "card_subq": 3000, "card_subt": 3},
  "10053" : { "card_name": "Amazon Business Prime American Express Card", "card_bank": "American Express", "card_brand": "Amazon", "card_network": CardNetwork.AmericanExpress, "card_type": CardType.Business, "card_url": "amazon-business-prime", "card_link": "https://www.amazon.com/gp/product/B07984JN3L/", "card_image": null, "card_af": 0, "card_ftf": 0, "card_apr": "19.49-27.49", "card_caf": "5|3", "card_lpf": "<=39", "card_chip": true, "card_material": "Metal", "card_ttp": true, "card_weight": 14, "card_color": "#1c1c1c", "card_redemption": CardRedemption.CashBack, "card_caapr": 29.99, "card_lpapr": 29.99, "card_subv": 10000, "card_subq": 3000, "card_subt": 3},
  "10054" : { "card_name": "Bank of America Premium Rewards credit card", "card_bank": "Bank of America", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "bofa-pr", "card_link": "https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/", "card_image": null, "card_af": 95, "card_ftf": 0, "card_btf": 4, "card_apr": "21.24-29.24", "card_caf": 4, "card_lpf": "<=40", "card_chip": true, "card_material": "Metal", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#272829", "card_redemption": CardRedemption.Points, "card_caapr": "24.24-29.24", "card_btapr": "21.24-29.24", "card_lpapr": 29.99, "card_subv": 60000, "card_subq": 4000, "card_subt": 3},
  "10055" : { "card_name": "PenFed Platinum Rewards Visa", "card_bank": "Pentagon Federal", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "penfed-platinum", "card_link": "https://www.penfed.org/credit-cards/platinum-rewards-visa", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 3, "card_apr": 17.99, "card_caf": 0, "card_lpf": "<=28", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#9ba9c0", "card_redemption": CardRedemption.Points, "card_caapr": 17.99, "card_btapr": 17.99, "card_subv": 15000, "card_subq": 1500, "card_subt": 3},
  "10056" : { "card_name": "PenFed Power Cash Rewards Visa", "card_bank": "Pentagon Federal", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_url": "penfed-power", "card_link": "https://www.penfed.org/credit-cards/power-cash-rewards-visa", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 3, "card_apr": 17.99, "card_caf": 0, "card_lpf": "<=28", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#152945", "card_redemption": CardRedemption.CashBack, "card_caapr": 17.99, "card_btapr": 17.99, "card_subv": 10000, "card_subq": 1500, "card_subt": 3},
  "10057" : { "card_name": "PenFed Gold Visa", "card_bank": "Pentagon Federal", "card_network": CardNetwork.Visa, "card_type": CardType.Personal, "card_redemption": CardRedemption.None, "card_url": "penfed-gold", "card_link": "https://www.penfed.org/credit-cards/gold-visa", "card_image": null, "card_af": 0, "card_ftf": 0, "card_btf": 3, "card_apr": 17.99, "card_caf": 0, "card_lpf": "<=28", "card_chip": true, "card_material": "Plastic", "card_il": CardInfoLocation.Back, "card_ttp": true, "card_color": "#d6b260", "card_caapr": 17.99, "card_btapr": 17.99, }
};

//gets one card from its ID. Accepts the card id and returns a promise. 
export async function getOneCardByID(id: string): Promise<CardObject | undefined> {
  if (id in card_table) {
    const cardObject = card_table[id]
    cardObject.card_id = id
    return cardObject
  } 
  return undefined
}
  
//finds the first card with the given url
export async function getOneCardByURL(url: string): Promise<CardObject | undefined> {
  const idAndCardObject = Object.entries(card_table).find(([id, obj]) => obj.card_url === url);
  if (idAndCardObject) {
    const [id, card] = idAndCardObject
    card.card_id = id
    return card
  }
  return undefined
} 

//gets cards from the card_bank stored in the card object.
export async function getCardsFromBankName(bank:BankObject): Promise<CardObject[]> {
  const cardList = Object.values(card_table).filter((cardObj) => cardObj.card_bank === bank.bank_name);
  return cardList
} 

//gets cards from the card_brand stored in the card object.
export async function getCardsFromBrandName(brand:BrandObject): Promise<CardObject[]> {
  const cardList = Object.values(card_table).filter((cardObj) => cardObj.card_brand === brand.brand_name);
  return cardList
} 
  
//gets an ordered list of (results)amount of cards sorted by a property
export async function orderCards(param:string, results:number): Promise<CardObject[] | undefined[]> {
  return [undefined]
}

//gets all cards in the databae (depreciated)
export async function getCards() {
  const cardList = Object.values(card_table)
  return cardList;
}

//gets the image of a card 
export async function getCardImage(card: CardObject) {
  return undefined;
}

